//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.PopularCompanies = new HashSet<PopularCompany>();
            this.Reviews = new HashSet<Review>();
            this.TopCompanies = new HashSet<TopCompany>();
            this.Experiences = new HashSet<Experience>();
            this.NewCompanies = new HashSet<NewCompany>();
        }
    
        public int Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Description { get; set; }
        public string Company_Logo { get; set; }
        public string Company_CoverPhoto { get; set; }
        public string Company_Location { get; set; }
        public string Company_Website { get; set; }
        public string Company_Contact { get; set; }
        public double Company_CRating { get; set; }
        public int Company_NoOfEmployees { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopularCompany> PopularCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopCompany> TopCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experience> Experiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewCompany> NewCompanies { get; set; }
    }
}
