//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int Education_Id { get; set; }
        public int Education_UserId { get; set; }
        public string Education_DegreeName { get; set; }
        public string Education_InstituteName { get; set; }
        public System.DateTime Education_StartDate { get; set; }
        public System.DateTime Education_EndDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
