//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Exp_Id { get; set; }
        public int Exp_CompanyId { get; set; }
        public int Exp_UserId { get; set; }
        public System.DateTime Exp_StartDate { get; set; }
        public System.DateTime Exp_EndDate { get; set; }
        public string Exp_Designation { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
