//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HuntSmartEntities1 : DbContext
    {
        public HuntSmartEntities1()
            : base("name=HuntSmartEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<EmailVerificationCode> EmailVerificationCodes { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
        public virtual DbSet<NewCompany> NewCompanies { get; set; }
        public virtual DbSet<PasswordVerificationCode> PasswordVerificationCodes { get; set; }
        public virtual DbSet<PopularCompany> PopularCompanies { get; set; }
        public virtual DbSet<RatingQuestion> RatingQuestions { get; set; }
        public virtual DbSet<RatingResponse> RatingResponses { get; set; }
        public virtual DbSet<Reply> Replies { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<TopCompany> TopCompanies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSkill> UserSkills { get; set; }
    }
}
