//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordVerificationCode
    {
        public int PasswordVerificationCode_Id { get; set; }
        public string PasswordVerificationCode_Value { get; set; }
        public System.DateTime PasswordVerificationCode_CreationTime { get; set; }
        public int PasswordVerificationCode_UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
