//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopularCompany
    {
        public int PopularCompany_Id { get; set; }
        public int PopularCompany_CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
