//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingResponse
    {
        public int RatingResponse_Id { get; set; }
        public int RatingResponse_ReviewId { get; set; }
        public int RatingResponse_RatingQuestionId { get; set; }
        public double RatingResponse_Result { get; set; }
    
        public virtual RatingQuestion RatingQuestion { get; set; }
        public virtual Review Review { get; set; }
    }
}
