//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public int Reply_Id { get; set; }
        public string Reply_Description { get; set; }
        public System.DateTime Reply_Time { get; set; }
        public int Reply_CommentId { get; set; }
        public int Reply_UserId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual User User { get; set; }
    }
}
