//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuntSmart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Educations = new HashSet<Education>();
            this.EmailVerificationCodes = new HashSet<EmailVerificationCode>();
            this.Experiences = new HashSet<Experience>();
            this.PasswordVerificationCodes = new HashSet<PasswordVerificationCode>();
            this.Replies = new HashSet<Reply>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int User_Id { get; set; }

        [Required(ErrorMessage = "Enter Your First Name")]
        public string User_FirstName { get; set; }

        [Required(ErrorMessage = "Enter Your Last Name")]
        public string User_LastName { get; set; }

        [Required(ErrorMessage = "Enter Your Email Address")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [Remote("IsUserExists", "Account", HttpMethod = "POST", ErrorMessage = "Email Already Registered")]
        public string User_Email { get; set; }

        public bool User_EmailVerifStatus { get; set; }

        [Required(ErrorMessage = "Enter Password of length 8-20 chracter long")]
        [StringLength(20, MinimumLength = 8)]
        public string User_Password { get; set; }
        public string User_Description { get; set; }
        public string User_ContactNo { get; set; }

        [Required(ErrorMessage = "Select your gender")]
        public string User_Gender { get; set; }

        [Required(ErrorMessage = "Select your Date of birth")]
        public string User_DOB { get; set; }

        public string User_Dp { get; set; }
        public string User_CoverPhoto { get; set; }
        public string User_AccountCreationDate { get; set; }
        public bool User_EmailPrivacyStatus { get; set; }
        public bool User_ContactNoPrivacyStatus { get; set; }
        public bool User_DOBPrivacyStatus { get; set; }
        public bool User_NamePrivacyStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Education> Educations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailVerificationCode> EmailVerificationCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experience> Experiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PasswordVerificationCode> PasswordVerificationCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reply> Replies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual UserSkill UserSkill { get; set; }
    }
}
